import unittest
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT_JS_PATH = REPO_ROOT / "script.js"
STYLES_CSS_PATH = REPO_ROOT / "styles.css"
INDEX_HTML_PATH = REPO_ROOT / "index.html"
MAIN_PY_PATH = REPO_ROOT / "main.py"


class ProjectPageUiTests(unittest.TestCase):
    def test_page_data_model_wiring_exists(self):
        script = SCRIPT_JS_PATH.read_text(encoding="utf-8")
        self.assertIn("function normalizePage(raw) {", script)
        self.assertIn("function normalizeProjectSubpage(raw = {}, index = 0, usedIds = new Set()) {", script)
        self.assertIn("function normalizeProjectSubpages(rawSubpages = []) {", script)
        self.assertIn("function getProjectSubpageDescendantIds(project, subpageId) {", script)
        self.assertIn("page: normalizePage(project.page),", script)
        self.assertIn("subpages: normalizeProjectSubpages(project.subpages),", script)
        self.assertIn("deliverablePagesMigratedToProjectSubpages:", script)
        # Legacy deliverable pages remain normalized for storage compatibility, but are not edited.
        self.assertIn("page: normalizePage(deliverable.page),", script)

    def test_page_editor_controller_exists(self):
        script = SCRIPT_JS_PATH.read_text(encoding="utf-8")
        self.assertIn("function openProjectPage(project, subpage = null) {", script)
        self.assertNotIn("function openDeliverablePage(project, deliverable) {", script)
        self.assertIn("function serializePageHtml(editor) {", script)
        self.assertIn("function hydratePageImages(editor) {", script)
        self.assertIn("function flattenLegacyPageItems(editor) {", script)
        self.assertIn("flattenLegacyPageItems(editor);", script)
        self.assertIn("function insertPageTodo() {", script)
        self.assertIn("function normalizePageChecklistItems(editor) {", script)
        self.assertIn("normalizePageChecklistItems(editor);", script)
        self.assertNotIn("function insertPageItem(tag) {", script)
        self.assertNotIn("function handlePageItemEnter(editor) {", script)
        self.assertIn("function normalizePageLinkHref(url) {", script)
        self.assertIn('openExternalUrl(link.getAttribute("href"));', script)
        self.assertIn("function renderPageChildLinks(project, activeSubpage = null) {", script)
        self.assertIn("function createProjectSubpageFromSlash() {", script)
        self.assertIn("function applyPageFindHighlights({ preserveIndex = true, scroll = false } = {}) {", script)
        self.assertIn("function stepPageFindMatch(delta) {", script)
        self.assertIn("function handlePageFindInput(event) {", script)
        self.assertIn("function handlePageFindKeydown(event) {", script)
        self.assertIn("function focusPageFindInput() {", script)
        self.assertIn("function createPageFindDomRange(parts, match) {", script)
        self.assertIn("function renderPageFindHighlights() {", script)
        self.assertIn("function scrollPageFindMatchIntoView(match) {", script)
        self.assertIn('new Highlight(...ranges)', script)
        self.assertNotIn("function wrapPageFindTextRange(", script)
        self.assertIn("function getActivePagePdfPayload() {", script)
        self.assertIn("async function publishActivePagePdf() {", script)
        self.assertIn("window.pywebview.api.publish_project_page_pdf(payload)", script)
        self.assertIn("unwrapPageFindHighlights(clone);", script)
        self.assertIn('document.getElementById("pageFindInput")?.addEventListener("input", handlePageFindInput);', script)
        self.assertIn('document.getElementById("pageFindInput")?.addEventListener("keydown", handlePageFindKeydown);', script)
        self.assertIn('document.getElementById("pageFindPrevBtn")?.addEventListener("click", () => stepPageFindMatch(-1));', script)
        self.assertIn('document.getElementById("pageFindNextBtn")?.addEventListener("click", () => stepPageFindMatch(1));', script)
        self.assertIn('document.getElementById("pagePublishPdfBtn")?.addEventListener("click", publishActivePagePdf);', script)
        self.assertIn("focusPageFindInput();", script)
        self.assertNotIn("function promptCreateProjectSubpage(parentId = null) {", script)
        self.assertNotIn("function renderProjectPageTree(project, activeSubpage = null) {", script)
        self.assertNotIn("function moveProjectSubpage(project, subpage, nextParentId = null) {", script)
        self.assertNotIn("function renderPageDeliverablesGrid(project) {", script)
        self.assertNotIn("function renderPageDeliverableMeta(", script)
        self.assertIn("function ensurePageViewReady() {", script)
        self.assertIn("function handlePageSlashBeforeInput(event) {", script)
        self.assertIn("function handlePageSlashKeydown(event) {", script)
        self.assertIn("function executePageSlashCommand(command, options = {}) {", script)
        self.assertIn("window.pywebview.api.save_page_asset", script)
        self.assertIn("window.pywebview.api.get_page_asset", script)

    def test_page_entry_points_exist(self):
        script = SCRIPT_JS_PATH.read_text(encoding="utf-8")
        self.assertNotIn("openDeliverablePage(project, deliverable)", script)
        self.assertIn("openProjectPage(project);", script)
        self.assertIn('className: "deliverable-card-open-page-action"', script)
        self.assertIn('title: "Open project notes"', script)
        self.assertIn('ariaLabel: "Open project notes"', script)
        self.assertIn("iconPath: NOTE_ICON_PATH", script)
        self.assertNotIn("Open deliverable page", script)
        self.assertNotIn("EXPAND_ICON_PATH", script)

    def test_page_view_markup_exists(self):
        html = INDEX_HTML_PATH.read_text(encoding="utf-8")
        self.assertIn('id="pageView"', html)
        self.assertIn('id="pageEditor"', html)
        self.assertIn('id="pageTitle"', html)
        self.assertIn('id="pageBreadcrumb"', html)
        self.assertIn('id="pageChildLinks"', html)
        self.assertIn('id="pageFindInput"', html)
        self.assertIn('id="pageFindCount"', html)
        self.assertIn('id="pageFindPrevBtn"', html)
        self.assertIn('id="pageFindNextBtn"', html)
        self.assertIn('id="pagePublishPdfBtn"', html)
        self.assertIn("Publish PDF", html)
        self.assertNotIn('id="projectPageTree"', html)
        self.assertNotIn('id="projectPageTreeList"', html)
        self.assertNotIn('id="projectPageAddRootSubpageBtn"', html)
        self.assertNotIn('id="pageDeliverablesGrid"', html)
        self.assertNotIn('id="pageAddDeliverableBtn"', html)
        self.assertNotIn('id="pageMeta"', html)
        self.assertIn('id="pageSlashMenu"', html)
        self.assertNotIn('class="page-toolbar"', html)
        self.assertNotIn('data-page-cmd=', html)
        self.assertNotIn('data-page-block=', html)
        self.assertNotIn('id="pageTextColorInput"', html)
        self.assertNotIn('id="pageInsertImageBtn"', html)
        self.assertNotIn('data-page-action="action"', html)
        self.assertNotIn('data-page-action="coordination"', html)
        self.assertNotIn('data-page-action="untag"', html)
        self.assertIn('id="pageImageInput"', html)

    def test_page_view_styles_exist(self):
        css = STYLES_CSS_PATH.read_text(encoding="utf-8")
        self.assertIn(".page-view {", css)
        self.assertIn(".page-editor {", css)
        self.assertIn(".page-slash-menu {", css)
        self.assertIn(".page-slash-menu-header {", css)
        self.assertIn(".page-slash-menu-shortcut {", css)
        self.assertIn(".page-slash-menu-item {", css)
        self.assertIn(".page-slash-color-swatch {", css)
        self.assertIn(".page-find {", css)
        self.assertIn("#pageFindInput {", css)
        self.assertIn(".page-find-match {", css)
        self.assertIn(".page-find-match.is-active {", css)
        self.assertIn("::highlight(page-find-match) {", css)
        self.assertIn("::highlight(page-find-active) {", css)
        self.assertIn(".page-view-publish {", css)
        self.assertIn(".page-child-links {", css)
        self.assertIn(".page-child-link {", css)
        self.assertIn(".page-checklist-item {", css)
        self.assertIn(".page-checklist-checkbox {", css)
        self.assertNotIn(".page-toolbar {", css)
        self.assertNotIn(".page-fmt-btn {", css)
        self.assertNotIn(".page-item {", css)
        self.assertNotIn(".page-item-badge[data-tag=\"coordination\"] {", css)
        self.assertNotIn(".project-page-tree {", css)
        self.assertNotIn(".project-page-tree-row {", css)
        self.assertNotIn(".project-page-parent-select {", css)
        self.assertNotIn(".page-deliverable-card {", css)
        self.assertNotIn(".page-meta {", css)

    def test_backend_page_asset_api_exists(self):
        main_py = MAIN_PY_PATH.read_text(encoding="utf-8")
        self.assertIn("def save_page_asset(self, owner_key, data_url, filename=\"\"):", main_py)
        self.assertIn("def get_page_asset(self, asset_path, max_size=1600):", main_py)
        self.assertIn("def _resolve_page_asset_path(self, asset_path):", main_py)
        self.assertIn("def publish_project_page_pdf(self, payload):", main_py)
        self.assertIn("def _prepare_project_page_pdf_html(self, raw_html):", main_py)


if __name__ == "__main__":
    unittest.main()
